version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: "terraform"
    directories:
      - "/terraform/modules/*"
      - "/terraform/test-fixtures/modules"
    schedule:
      interval: "weekly"
    groups:
      terraform:
        patterns: ["*"]
